// <auto-generated />
using System;
using AUTENTICADOR.src.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backendOrkletti.Migrations
{
    [DbContext(typeof(PostgreContext))]
    [Migration("20240310153035_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendOrkletti.src.Model.Entity.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cd_community");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dt_createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("ds_description");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("bl_image");

                    b.Property<string>("ProfileId")
                        .HasColumnType("text")
                        .HasColumnName("cd_profile_id");

                    b.Property<string>("Tittle")
                        .HasColumnType("text")
                        .HasColumnName("ds_title");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("community");
                });

            modelBuilder.Entity("backendOrkletti.src.Model.Entity.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("cd_profile_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("ds_bio");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("ds_fist_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("ds_last_name");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("bytea")
                        .HasColumnName("bl_profile_image");

                    b.HasKey("Id");

                    b.ToTable("profile");
                });

            modelBuilder.Entity("backendOrkletti.src.Model.Entity.Community", b =>
                {
                    b.HasOne("backendOrkletti.src.Model.Entity.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
